### ISSUE TITLE
CSS example targeting html which does not exist in shadow root

### ISSUE THREAD

**Issue by e111077** [modernweb-dev/web#459]
Heya, the example here doesn't seem to be green because it is selecting `html` but the example is in a shadow root. Not sure if that's intentional as the following text says it should have 'cornflowerblue' as a bg

https://github.com/modernweb-dev/web/blob/ebe2cef0657e27b69d120fe67d0dd272b3b99ef2/docs/guides/going-buildless/css.md#L59

https://modern-web.dev/guides/going-buildless/css/

**Comment by daKmoR** [comment]
@bennypowers we probably should check this example... maybe we can make it "simpler" and/or easier to follow 🤔

**Comment by bennypowers** [comment]
the problem here was I selected for `html` instead of `:host`, being that this is all rendered in the shadow root of an `<mdjs-preview>`

this css should fix it

```css
:host {
  --my-background-color: green;
  --my-font-size: 12px;
}

article p {
  --my-font-size: 24px;
  --my-background-color: cornflowerblue;
  --p-padding-horizontal: 12px;
}

p {
  display: inline-block;
  border-radius: 4px;
  padding: 4px var(--p-padding-horizontal,6px);
  background-color: var(--my-background-color);
  font-size: var(--my-font-size);
}
```

<img width="922" alt="Screen Shot 2020-08-31 at 23 40 26" src="https://user-images.githubusercontent.com/1466420/91766538-61416280-ebe3-11ea-8f6c-99093bca820a.png">
